Feature/19
MetaCell/scicrunch-antibody-registry pull request #48
Opened 2022-09-08 13:03 UTC by Aiga115

FAQs section added, according styles applied 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/67194168/189128824-5742c081-61ae-49b1-959a-8144a72244d9.png">

2022-09-08 14:36 UTC, Aiga115 commented
> @Aiga115 can you please fix the conflicts?

Yes, sure

2022-09-12 09:29 UTC, filippomc requested changes
Good job @Aiga115 , the frontend implementation is accurate and code is clean.

A few notes before merging:
- Linting is not consistent (see comment)
- The page should have address /faq
- The page should be reachable from the header menu
- Commits refer to issue #28, should be #19 (nothing we can do now, just to keep in mind for the next commits)
- The text inside the single FAQs is not formatted and sometimes is not easily readable -- please follow the typography from the original document

2022-09-12 09:29 UTC, filippomc commented on applications/areg-portal/frontend/src/components/Support/FAQs.tsx
> +    faqBox: {
The linting is not consistent. Should be 2 spaces, not 4. One strategy is to use the VSCode ESLint plugin

2022-09-15 09:23 UTC, filippomc approved these changes

2022-09-15 09:23 UTC, merged